CREATE TABLE DEPARTMENTS(
DEPT_NO VARCHAR(10) PRIMARY KEY,
DEPT_NAME VARCHAR(20) NOT NULL
)

CREATE TABLE EMPLOYEES(
EMP_NO INTEGER PRIMARY KEY,
BIRTH_DATE VARCHAR(10) NOT NULL,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
GENDER CHAR(1) NOT NULL,
HIRE_DATE VARCHAR(10) NOT NULL
)


CREATE TABLE DEPT_EMP(
EMP_NO INTEGER REFERENCES EMPLOYEES(EMP_NO),
DEPT_NO VARCHAR(10) REFERENCES DEPARTMENTS(DEPT_NO),
FROM_DATE VARCHAR(10) NOT NULL,
TO_DATE VARCHAR(10) NOT NULL,
PRIMARY KEY (EMP_NO ,DEPT_NO,FROM_DATE)
)

CREATE TABLE DEPT_MANAGER(
DEPT_NO VARCHAR(10) REFERENCES  DEPARTMENTS(DEPT_NO),
EMP_NO INTEGER REFERENCES  EMPLOYEES(EMP_NO),
FROM_DATE VARCHAR(10) NOT NULL,
TO_DATE VARCHAR(10) NOT NULL,
PRIMARY KEY (DEPT_NO,EMP_NO,FROM_DATE)
)

CREATE TABLE SALARIES(
EMP_NO INTEGER REFERENCES EMPLOYEES(EMP_NO),
SALARY INTEGER NOT NULL,
FROM_DATE VARCHAR(10),
TO_DATE VARCHAR(10) NOT NULL,
PRIMARY KEY (EMP_NO,FROM_DATE)
)

CREATE TABLE TITLES(
EMP_NO INTEGER REFERENCES EMPLOYEES(EMP_NO),
TITLE VARCHAR(20) NOT NULL,
FROM_DATE VARCHAR(10),
TO_DATE VARCHAR(10) NOT NULL,
PRIMARY KEY (EMP_NO,FROM_DATE)
)
